### ISSUE TITLE
Compiler reporting functions as not existing

### ISSUE THREAD

**Issue by seanny** [Southclaws/pawn#175] opened 2017-06-08 11:34 UTC
Hi, I noticed a bug where the compiler says my functions do not exist, when in fact they do.

> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(585) : error 017: undefined symbol "SendGlobalMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(587) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1108) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1123) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1131) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1137) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1159) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1340) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1357) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1365) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1371) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1393) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1486) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1490) : error 017: undefined symbol "SaveAccount"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1493) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1496) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1499) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1507) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1558) : error 017: undefined symbol "SendGlobalMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1752) : error 017: undefined symbol "WriteLog"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1788) : error 017: undefined symbol "SaveAccount"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(1982) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(2049) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(2235) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(2520) : error 017: undefined symbol "SendAdminMessage"
> C:\Users\seanm\Documents\SAMP\gamemodes\SAS-RP.pwn(2676) : error 017: undefined symbol "SendHelperMessage"
> 
> Compilation aborted.
> 
> Pawn compiler 3.10.2	 	 	Copyright (c) 1997-2006, ITB CompuPhase
> 
> 
> 26 Errors.

All the "undefined symbols" do all exist and no changes were made to them prior to my current change, in the same file.

All of the mentioned functions are stock type functions.

**Comment by seanny** [comment] 2017-06-08 11:55
I moved all the problematic stock functions to the top of the script, and it seems to magically compile as normal again. This is something I've never experienced before and it doesn't happen on the original SAMP compiler.

**Comment by Dayvison** [comment] 2017-06-08 14:09
You left a open bracket {

**Comment by seanny** [comment] 2017-06-08 20:07
There was no open brackets, I checked the script. In the end, I had to move the problematic stocks to the top of the script. It seemed like having the stocks after the function that calls them propped up these false errors, hiding real compile errors. I even tested this against the original SA-MP compiler, and it only reported expected errors and not undefined symbols.

**Comment by Y-Less** [comment] 2017-06-08 20:30
Can you provide a minimal repro?

**Comment by seanny** [comment] 2017-06-10 20:32
I've since been unable to reproduce it, I tried reproducing it in bare.pwn (gamemodes/bare.pwn) but it seems to compile normally.

The issue seems to have been related to new features I added to my gamemode, which I've since rewritten and it seems to have fixed itself.

**Comment by YashasSamaga** [comment] 2018-01-03 15:39
@Southclaws close?

**Comment by Southclaws** [comment] 2018-01-03 15:59
This sounds like it may have been caused by include name shadowing - explanation [here](https://github.com/Misiur/YSI-Includes/wiki/Include-Guards). Closing for now.

**Closed by Southclaws** 2018-01-03 15:59 UTC
